FROM openjdk:17-jdk-slim
WORKDIR /app
COPY target/backend.jar /app/backend.jar
EXPOSE 7778
CMD ["java", "-jar", "backend.jar", "--spring.datasource.url=jdbc:mysql://mysql_service:3306/苍穹杯?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true", "--spring.datasource.username=root", "--spring.datasource.password=root_password", "--server.port=7778"]
